name: speech
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - archspec=0.2.3
  - asttokens=2.4.1
  - boltons=24.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.2
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - debugpy=1.8.1
  - decorator=5.1.1
  - distro=1.9.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - fmt=10.2.1
  - frozendict=2.4.4
  - icu=73.2
  - idna=3.6
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - ipykernel=6.29.3
  - ipython=8.24.0
  - jedi=0.19.1
  - jsonpatch=1.33
  - jsonpointer=2.4
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.2
  - ld_impl_linux-64=2.40
  - libarchive=3.7.2
  - libcurl=8.7.1
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libiconv=1.17
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libsodium=1.0.18
  - libsolv=0.7.28
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.12.6
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - matplotlib-inline=0.1.7
  - menuinst=2.0.2
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - openssl=3.3.0
  - packaging=24.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.0
  - pluggy=1.4.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.22
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0
  - python_abi=3.10
  - pyzmq=26.0.3
  - readline=8.2
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.31.0
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - setuptools=69.5.1
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.4
  - tqdm=4.66.2
  - traitlets=5.14.3
  - truststore=0.8.0
  - typing_extensions=4.11.0
  - urllib3=2.2.1
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.2.6
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zipp=3.17.0
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - accelerate==0.31.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - contourpy==1.2.1
      - cycler==0.12.1
      - filelock==3.14.0
      - fonttools==4.53.0
      - frozenlist==1.4.1
      - fsspec==2024.6.0
      - grpcio==1.64.1
      - huggingface-hub==0.23.3
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - lightning-utilities==0.11.2
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - mpmath==1.3.0
      - multidict==6.0.5
      - networkx==3.3
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.40
      - nvidia-nvtx-cu12==12.1.105
      - pandas==2.2.2
      - peft==0.11.1
      - pillow==10.3.0
      - protobuf==4.25.3
      - pyparsing==3.1.2
      - pytorch-lightning==2.2.5
      - pytz==2024.1
      - pyyaml==6.0.1
      - regex==2024.5.15
      - safetensors==0.4.3
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - sympy==1.12.1
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - torch==2.3.1
      - torchmetrics==1.4.0.post0
      - torchvision==0.18.1
      - transformers==4.41.2
      - triton==2.3.1
      - tzdata==2024.1
      - werkzeug==3.0.3
      - yarl==1.9.4
prefix: /home/XXX/miniforge3/envs/speech
