dataset:
  annotation_path: /media/LaCie/Annotation_20240521/BMS/labelint/total_EN_HNS.csv
  dico_label:
    0: 0
    1: 1
    "0": 0
    "1": 1
  feature_dir: /media/LaCie/Features/Clip_16_Frames
  feature_stride: 16
  feature_window: 16
  nb_segment: 16
  oversampling : True
dataset_name: bms_tractive
exp_config: Inverted
loader:
  batch_size: 16
loss: inverted_veriety
opt:
  epochs: 35
  learning_rate: 0.0001
  patience: 15
  weight_decay: 0.05
output_folder: ckpt/Neurips_V1_20240522/
test_cfg:
  max_seg_num: 200
  min_score: 0.001
  multiclass_nms: true
  pre_nms_topk: 2000
  voting_thresh: 0.7
test_split: test
train_cfg:
  center_sample: radius
  center_sample_radius: 1.5
  clip_grad_l2norm: 1.0
  cls_prior_prob: 0.01
  early_stopping: 15
  init_loss_norm: 100
train_split: train
val_split: validation
yaml_name: config_ENvsHNS
